//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignManager.Infrastructure.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CampaignManager.Infrastructure.Common.Resources.ApiMessagesResource", typeof(ApiMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Successfuly .
        /// </summary>
        internal static string AssetUploadedSuccess {
            get {
                return ResourceManager.GetString("AssetUploadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, while uploading the asset! please try again.
        /// </summary>
        internal static string AssetUploadFail {
            get {
                return ResourceManager.GetString("AssetUploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Client Found.
        /// </summary>
        internal static string ClientNotGound {
            get {
                return ResourceManager.GetString("ClientNotGound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Registering Client.
        /// </summary>
        internal static string ClientRegistedError {
            get {
                return ResourceManager.GetString("ClientRegistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Registered Not Successfully.
        /// </summary>
        internal static string ClientRegistedFailure {
            get {
                return ResourceManager.GetString("ClientRegistedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Registered Successfully.
        /// </summary>
        internal static string ClientRegistedSuccess {
            get {
                return ResourceManager.GetString("ClientRegistedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Created Successfully .
        /// </summary>
        internal static string DropCreated {
            get {
                return ResourceManager.GetString("DropCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Email Already Registered.
        /// </summary>
        internal static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save Email Subscription Data.
        /// </summary>
        internal static string EmailSubscriptionFailed {
            get {
                return ResourceManager.GetString("EmailSubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successfully.
        /// </summary>
        internal static string Logoutsuccessfully {
            get {
                return ResourceManager.GetString("Logoutsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3 Bucket Already Exist.
        /// </summary>
        internal static string S3BucketAlreadyExist {
            get {
                return ResourceManager.GetString("S3BucketAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3 Bucket Not Exist.
        /// </summary>
        internal static string S3BucketNotExist {
            get {
                return ResourceManager.GetString("S3BucketNotExist", resourceCulture);
            }
        }
    }
}
